---
title: ""Badanie determinant wpływających na przyjęcie na lepszą uczelnie""
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Column {data-width=650}
-----------------------------------------------------------------------
library(ggplot2)
### Wykres zależności temperatury od miesięcy

```{r}
mytheme_main <- theme( panel.background = element_blank(), 
  panel.grid.major = element_line(colour = "#dddddd"), 
  axis.ticks = element_line(colour = "#dddddd") )

mytheme_map <- theme(
  panel.background = element_blank(), axis.title.x = element_blank(),
  axis.text = element_blank(), axis.line.x = element_blank(),
  axis.line.y = element_blank(), axis.title.y = element_blank(),
  axis.ticks.x = element_blank(), axis.ticks.y = element_blank() )

mydata$tooltip <- row.names(mydata)

# Wizualizacja
gg_point_1 <- ggplot(mydata, aes(x = Month, y = Temp, 
         tooltip = tooltip ) ) + 
    geom_point_interactive(size=3)


# htmlwidget call
ggiraph(code = {print(gg_point_1 + mytheme_main)}, height = 6)
```


Column {data-width=350}
-----------------------------------------------------------------------

### Wykres zależności średniej zawartość ozonu od miesięcy

```{r}
# Wizualizacja
gg_point_1 <- ggplot(mydata, aes(x = Month, y = Ozone, 
         tooltip = tooltip ) ) + 
    geom_point_interactive(size=3)


# htmlwidget call
ggiraph(code = {print(gg_point_1 + mytheme_main)}, height = 6)
```



### Wykres zależności średniej prędkość wiatru od miesięcy

```{r}

```

